spreadsheetId: 1gyIPIDpG8p8bAclC7pdpqAlMoke2DYqgHa61hfBCIAw
scorecardSheetName: Scorecard
bracketSheetName: Bracket

numberOfTeams: 32
playersPerTeam: 2
rounds:
  - numberOfEpisodes: 3
  - numberOfEpisodes: 3
  - numberOfEpisodes: 3
  - numberOfEpisodes: 3
  - numberOfEpisodes: 5

origin:
  row: 12
  col: 2

teamCard:
  height: 10
  team:
    name:
      row: 0
      col: 1
    color:
      row: 0
      col: 2
    server:
      row: 0
      col: 3
    display:
      row: 7
      col: 3
    seed:
      row: 8
      col: 3
  player:
    name:
      row: 2
      col: 1
      direction: VERTICAL
    pronouns:
      row: 2
      col: 2
      direction: VERTICAL
    discord:
      row: 2
      col: 3
      direction: VERTICAL
    crowns:
      row: 5
      col: 1
      direction: VERTICAL
    achievement:
      row: 5
      col: 2
      direction: VERTICAL
    twitter:
      row: 5
      col: 3
      direction: VERTICAL
    twitch:
      row: 7
      col: 1
      direction: VERTICAL
  round:
    score:
      row: 2
      col: 5
      direction: VERTICAL
    total:
      row: 7
      col: 5
    status:
      row: 7
      col: 6