spreadsheetId: 1cvGTnt6UIBzLqQnRmPIRy6J5r6cRryvtABD4PyF5r3I
numberOfTeams: 32
playersPerTeam: 2

teamCard:
  sheetName: Scorecard
  origin:
    row: 12
    col: 2
  height: 10
  team:
    name:
      row: 0
      col: 1
    color:
      row: 0
      col: 2
    server:
      row: 0
      col: 3
    display:
      row: 7
      col: 3
    seed:
      row: 8
      col: 3
  player:
    name:
      row: 2
      col: 1
      direction: VERTICAL
    pronouns:
      row: 2
      col: 2
      direction: VERTICAL
    discord:
      row: 2
      col: 3
      direction: VERTICAL
    crowns:
      row: 5
      col: 1
      direction: VERTICAL
    achievement:
      row: 5
      col: 2
      direction: VERTICAL
    twitter:
      row: 5
      col: 3
      direction: VERTICAL
    twitch:
      row: 7
      col: 1
      direction: VERTICAL
  round:
    episodeCount: [3, 3, 3, 4, 5]
    score:
      row: 2
      col: 5
      direction: VERTICAL
    total:
      row: 7
      col: 5
    status:
      row: 7
      col: 6
    nameBadge:
      row: 8
      col: 5
    roundBadge:
      row: 8
      col: 6

bracket:
  sheetName: Bracket
  cells:
    - col: 2
      rows: [3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65]
      name: Round 1
      teamCardRoundIdx: 0
    - col: 5
      rows: [4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64]
      name: Round 2
      teamCardRoundIdx: 1
    - col: 8
      rows: [6, 14, 22, 30, 38, 46, 54, 62]
      name: Quarterfinals
      teamCardRoundIdx: 2
    - col: 11
      rows: [10, 26, 42, 58]
      name: Semifinals
      teamCardRoundIdx: 3
    - col: 14
      rows: [60, 64]
      name: 3rd Place
      teamCardRoundIdx: 4
    - col: 14
      rows: [18, 50]
      name: Finals
      teamCardRoundIdx: 4
    - col: 17
      rows: [33]
      name: First Place
      teamCardRoundIdx: -1
    - col: 17
      rows: [35]
      name: Second Place
      teamCardRoundIdx: -1
    - col: 17
      rows: [61]
      name: Third Place
      teamCardRoundIdx: -1
    - col: 17
      rows: [63]
      name: Fourth Place
      teamCardRoundIdx: -1
